"""add position_id columns to responsibility tables

Revision ID: 2139f5d4ee4f
Revises: f0414d4c1fe3
Create Date: 2023-10-22 10:16:49.051460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2139f5d4ee4f'
down_revision = 'f0414d4c1fe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('position_responsibility_department_id_fkey', 'position', type_='foreignkey')
    op.drop_constraint('position_responsibility_department_group_id_fkey', 'position', type_='foreignkey')
    op.drop_column('position', 'responsibility_department_group_id')
    op.drop_column('position', 'responsibility_department_id')
    op.add_column('responsibility_department', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'responsibility_department', 'position', ['position_id'], ['id'])
    op.add_column('responsibility_department_group', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'responsibility_department_group', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responsibility_department_group', type_='foreignkey')
    op.drop_column('responsibility_department_group', 'position_id')
    op.drop_constraint(None, 'responsibility_department', type_='foreignkey')
    op.drop_column('responsibility_department', 'position_id')
    op.add_column('position', sa.Column('responsibility_department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('position', sa.Column('responsibility_department_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('position_responsibility_department_group_id_fkey', 'position', 'responsibility_department_group', ['responsibility_department_group_id'], ['id'])
    op.create_foreign_key('position_responsibility_department_id_fkey', 'position', 'responsibility_department', ['responsibility_department_id'], ['id'])
    # ### end Alembic commands ###
