"""add order column

Revision ID: 4bd1699af88a
Revises: 84abd49904e5
Create Date: 2023-12-02 15:31:18.009017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd1699af88a'
down_revision = '84abd49904e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order')
    # ### end Alembic commands ###
