"""empty message

Revision ID: 51422a86635c
Revises: 9d0578cb45b4
Create Date: 2023-12-22 21:23:11.150262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51422a86635c'
down_revision = '9d0578cb45b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
