"""Add check_list_id in inspections and total_grade to check_list

Revision ID: 559c5c0c64bc
Revises: 0d16fd40da6b
Create Date: 2023-09-25 21:00:58.491403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559c5c0c64bc'
down_revision = '0d16fd40da6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_list', sa.Column('total_grade', sa.Integer(), nullable=True))
    op.add_column('inspection', sa.Column('check_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inspection', 'check_list', ['check_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_column('inspection', 'check_list_id')
    op.drop_column('check_list', 'total_grade')
    # ### end Alembic commands ###
