"""empty message

Revision ID: 6ecc016bce05
Revises: 4bd1699af88a
Create Date: 2023-12-09 23:43:23.654042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecc016bce05'
down_revision = '4bd1699af88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
