"""add parent question

Revision ID: 84abd49904e5
Revises: e77a47cfa8dc
Create Date: 2023-11-27 20:51:24.229598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84abd49904e5'
down_revision = 'e77a47cfa8dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_department_id_fkey', 'profile', type_='foreignkey')
    op.drop_constraint('profile_department_group_id_fkey', 'profile', type_='foreignkey')
    op.drop_column('profile', 'department_group_id')
    op.drop_column('profile', 'department_id')
    op.add_column('questions', sa.Column('parent_question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'questions', ['parent_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'parent_question_id')
    op.add_column('profile', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profile', sa.Column('department_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profile_department_group_id_fkey', 'profile', 'department_group', ['department_group_id'], ['id'])
    op.create_foreign_key('profile_department_id_fkey', 'profile', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###
