"""add inspection and employees modules

Revision ID: 996180ad0be8
Revises: 53cbd498dc24
Create Date: 2023-09-07 23:41:14.917761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996180ad0be8'
down_revision = '53cbd498dc24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility_department_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_group_id'], ['department_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('responsibility_question_id', sa.Integer(), nullable=True),
    sa.Column('responsibility_department_group_id', sa.Integer(), nullable=True),
    sa.Column('responsibility_department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsibility_department_group_id'], ['responsibility_department_group.id'], ),
    sa.ForeignKeyConstraint(['responsibility_department_id'], ['responsibility_department.id'], ),
    sa.ForeignKeyConstraint(['responsibility_question_id'], ['responsibility_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    op.drop_table('inspection_question')
    op.drop_table('employee_result')
    op.drop_table('inspection')
    op.drop_table('position')
    op.drop_table('responsibility_question')
    op.drop_table('responsibility_department_group')
    op.drop_table('responsibility_department')
    op.drop_table('profile')
    # ### end Alembic commands ###
