"""empty message

Revision ID: 9d0578cb45b4
Revises: 6ecc016bce05
Create Date: 2023-12-15 20:45:38.149956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0578cb45b4'
down_revision = '6ecc016bce05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inspection', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_column('inspection', 'user_id')
    # ### end Alembic commands ###
