"""add position id to profile

Revision ID: a2d4bc26d001
Revises: 996180ad0be8
Create Date: 2023-09-07 23:46:01.147889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d4bc26d001'
down_revision = '996180ad0be8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'position_id')
    # ### end Alembic commands ###
