"""add columns to profile

Revision ID: e77a47cfa8dc
Revises: 2139f5d4ee4f
Create Date: 2023-10-30 20:29:23.594275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77a47cfa8dc'
down_revision = '2139f5d4ee4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('department_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profile', 'department_group', ['department_group_id'], ['id'])
    op.create_foreign_key(None, 'profile', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'department_group_id')
    op.drop_column('profile', 'department_id')
    # ### end Alembic commands ###
