"""change responsibility question

Revision ID: f0414d4c1fe3
Revises: 559c5c0c64bc
Create Date: 2023-10-22 09:58:03.382019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0414d4c1fe3'
down_revision = '559c5c0c64bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('position_responsibility_question_id_fkey', 'position', type_='foreignkey')
    op.drop_column('position', 'responsibility_question_id')
    op.add_column('responsibility_question', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'responsibility_question', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responsibility_question', type_='foreignkey')
    op.drop_column('responsibility_question', 'position_id')
    op.add_column('position', sa.Column('responsibility_question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('position_responsibility_question_id_fkey', 'position', 'responsibility_question', ['responsibility_question_id'], ['id'])
    # ### end Alembic commands ###
